IMAGE MANIPULATION: FOR FRAMES IN VIDEOS

In [1]:
import cv2
import random

In [2]:
img = cv2.imread(r'C:\Users\hites\Desktop\robo\opencv_basics\assets\Ball.png', -1)

Image as numpy array:

In [3]:
print(img)

[[[216 217 212]
  [216 217 212]
  [216 217 212]
  ...
  [167 188 214]
  [167 188 214]
  [167 188 214]]

 [[216 217 212]
  [216 217 212]
  [216 217 212]
  ...
  [167 188 214]
  [167 188 214]
  [167 188 214]]

 [[216 217 212]
  [216 217 212]
  [216 217 212]
  ...
  [167 188 214]
  [167 188 214]
  [167 188 214]]

 ...

 [[182 195 198]
  [182 195 198]
  [182 195 198]
  ...
  [121 136 147]
  [120 135 146]
  [120 135 146]]

 [[180 193 196]
  [180 193 196]
  [180 193 196]
  ...
  [126 141 152]
  [125 140 151]
  [125 140 151]]

 [[180 193 196]
  [180 193 196]
  [179 192 195]
  ...
  [127 142 153]
  [126 141 152]
  [126 141 152]]]


In [4]:
print(type(img))

<class 'numpy.ndarray'>


In [5]:
print(img.shape)#height, width, channels(BGR in case of opencv)

(1080, 1300, 3)


Extracting nparray img : slicing, spliting:

In [ ]:
print(img[0][700:800])#range of pixels in img row of pixels

Manipulating pixels in img row of pixels:

In [7]:
# this will colour 1st 100 rows of image pixels with random colours:
for i in range(100):
    for j in range(img.shape[1]):#1st row of image
        img[i][j] = [random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)]

cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
#copy paste objects in an img:
ball = img[550:800, 100:440]
img[50:300, 900:1240] = ball

cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()